#!/bin/bash -x
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
echo BEGIN $(date '+%Y-%m-%d %H:%M:%S')
# determine which cloud we are in and set some variables
if [[ $(sudo dmidecode -s bios-version) =~ .*\.amazon ]]
then
  echo "This is AWS"
  DC=aws
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  HASHIQUBE_IP="10.9.99.11"
  HASHIQUBE_AWS_IP=${HASHIQUBE_AWS_IP}
  HASHIQUBE_AZURE_IP=${HASHIQUBE_AZURE_IP}
  HASHIQUBE_GCP_IP=${HASHIQUBE_GCP_IP}
  HOSTNAME=hashiqube-aws
  FQDN=hashiqube-aws.service.consul
elif [[ $(sudo dmidecode -s bios-version) =~ Google ]]
then
  echo "This is GCP"
  DC=gcp
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  HASHIQUBE_IP="10.9.99.12"
  HASHIQUBE_GCP_IP=${HASHIQUBE_GCP_IP}
  HASHIQUBE_AZURE_IP=${HASHIQUBE_AZURE_IP}
  HASHIQUBE_AWS_IP=${HASHIQUBE_AWS_IP}
  HOSTNAME=hashiqube-gcp
  FQDN=hashiqube-gcp.service.consul
else
  echo "This is Azure"
  DC=azure
  INSTANCE_PRIVATE_IP=$(hostname --all-ip-addresses | cut -d ' ' -f1)
  INSTANCE_IP=$(curl -s 'https://api.ipify.org?format=text')
  HASHIQUBE_IP="10.9.99.13"
  HASHIQUBE_AZURE_IP=${HASHIQUBE_AZURE_IP}
  HASHIQUBE_AWS_IP=${HASHIQUBE_AWS_IP}
  HASHIQUBE_GCP_IP=${HASHIQUBE_GCP_IP}
  HOSTNAME=hashiqube-azure
  FQDN=hashiqube-azure.service.consul
fi
# set hostname
echo "$HOSTNAME" > /etc/hostname
sudo hostname "$HOSTNAME"
sudo sed -i "s/.*127.0.0.1.*/127.0.0.1 $FQDN $HOSTNAME localhost/g" /etc/hosts
# install basetools
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install swapspace curl unzip jq git update-motd toilet figlet apt-transport-https ca-certificates gnupg-agent software-properties-common
# set motd
sudo mkdir -p /etc/update-motd.d
cat <<EOF | sudo tee /etc/update-motd.d/00-header
#!/bin/bash
/usr/bin/toilet --gay -f standard $(hostname) -w 170
printf "%s"
EOF
# install docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install --allow-downgrades --assume-yes docker.io
sudo usermod -aG docker ubuntu
sudo service docker restart
# install vagrant
sudo apt-get install -y vagrant
# clone and run hashiqube
sudo git clone https://github.com/star3am/hashiqube.git
cd hashiqube
# set different IPs for the nodes
for i in $(grep -Rlz '10.9.99.10' /hashiqube/); do sudo sed -i "s/10.9.99.10/$HASHIQUBE_IP/g" $i; done
# set different Hostnames for the nodes
for i in $(grep -Rlz 'hashiqube0' /hashiqube/); do sudo sed -i "s/hashiqube0/hashiqube-$DC/g" $i; done
# set different DCs for the nodes
for i in $(grep -Rlz 'dc1' /hashiqube/); do sudo sed -i "s/dc1/$DC/g" $i; done
sudo vagrant up --provision-with basetools,docker,vault,consul,nomad,boundary,waypoint
# cluster join
if [[ $HASHIQUBE_AZURE_IP ]]; then
  sudo vagrant ssh -c "consul join -wan ${HASHIQUBE_AZURE_IP}"
  sudo vagrant ssh -c "consul members -wan"
  sudo vagrant ssh -c "nomad server join ${HASHIQUBE_AZURE_IP}"
  sudo vagrant ssh -c "nomad server members"
fi
if [[ $HASHIQUBE_AWS_IP ]]; then
  sudo vagrant ssh -c "consul join -wan ${HASHIQUBE_AWS_IP}"
  sudo vagrant ssh -c "consul members -wan"
  sudo vagrant ssh -c "nomad server join ${HASHIQUBE_AWS_IP}"
  sudo vagrant ssh -c "nomad server members"
fi
if [[ $HASHIQUBE_GCP_IP ]]; then
  sudo vagrant ssh -c "consul join -wan ${HASHIQUBE_GCP_IP}"
  sudo vagrant ssh -c "consul members -wan"
  sudo vagrant ssh -c "nomad server join ${HASHIQUBE_GCP_IP}"
  sudo vagrant ssh -c "nomad server members"
fi
echo END $(date '+%Y-%m-%d %H:%M:%S')